project_id = "vspjxzbeooknotuxiefk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_password_change_enabled = true
enable_manual_linking = false

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[edge_functions]
enabled = true

[functions.openai-assistant-chat]
verify_jwt = false

[functions.create-team-member]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.delete-team-member]
verify_jwt = true