-- Complete migration to import all existing translations from JSON files

-- First, clear existing sample data
DELETE FROM translations WHERE is_system = true;

-- Add comprehensive indexes for performance
CREATE INDEX IF NOT EXISTS idx_translations_key_namespace_language ON translations (key, namespace, language);
CREATE INDEX IF NOT EXISTS idx_translations_language_namespace ON translations (language, namespace);
CREATE INDEX IF NOT EXISTS idx_translations_is_system ON translations (is_system);
CREATE INDEX IF NOT EXISTS idx_translations_search ON translations USING gin(to_tsvector('simple', key || ' ' || value));

-- Add audit columns for better tracking
ALTER TABLE translations 
ADD COLUMN IF NOT EXISTS version INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS last_modified_by UUID REFERENCES auth.users(id),
ADD COLUMN IF NOT EXISTS is_auto_translated BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}';

-- Import Slovak common translations
INSERT INTO translations (key, namespace, language, value, is_system) VALUES
-- Common buttons SK
('buttons.next', 'common', 'sk', 'Ďalej', true),
('buttons.back', 'common', 'sk', 'Späť', true),
('buttons.save', 'common', 'sk', 'Uložiť', true),
('buttons.saveAndExit', 'common', 'sk', 'Uložiť a ukončiť', true),
('buttons.complete', 'common', 'sk', 'Dokončiť registráciu', true),
('buttons.add', 'common', 'sk', 'Pridať', true),
('buttons.remove', 'common', 'sk', 'Odstrániť', true),
('buttons.edit', 'common', 'sk', 'Upraviť', true),
('buttons.cancel', 'common', 'sk', 'Zrušiť', true),
('buttons.confirm', 'common', 'sk', 'Potvrdiť', true),
('buttons.close', 'common', 'sk', 'Zavrieť', true),
('buttons.continue', 'common', 'sk', 'Pokračovať', true),
('buttons.saveSignature', 'common', 'sk', 'Uložiť podpis', true),
('buttons.delete', 'common', 'sk', 'Vymazať', true),
('buttons.deleting', 'common', 'sk', 'Vymazáva sa...', true),
('buttons.clearFilters', 'common', 'sk', 'Vymazať filtre', true),

-- Common navigation SK
('navigation.step', 'common', 'sk', 'Krok', true),
('navigation.of', 'common', 'sk', 'z', true),
('navigation.progress', 'common', 'sk', 'Postup', true),
('navigation.completed', 'common', 'sk', 'dokončené', true),
('navigation.steps', 'common', 'sk', 'krokov', true),
('navigation.overall', 'common', 'sk', 'Celkový postup', true),

-- Common status SK
('status.saving', 'common', 'sk', 'Ukladá sa...', true),
('status.saved', 'common', 'sk', 'Uložené', true),
('status.loading', 'common', 'sk', 'Načítava sa...', true),
('status.submitting', 'common', 'sk', 'Odosiela sa...', true),
('status.error', 'common', 'sk', 'Chyba', true),
('status.success', 'common', 'sk', 'Úspech', true),
('status.draft', 'common', 'sk', 'Koncept', true),
('status.completed', 'common', 'sk', 'Dokončené', true),
('status.inProgress', 'common', 'sk', 'Prebieha', true),
('status.next', 'common', 'sk', 'Nasledujúci', true),
('status.partiallyComplete', 'common', 'sk', 'Čiastočne vyplnené', true),
('status.active', 'common', 'sk', 'Aktívny', true),
('status.inactive', 'common', 'sk', 'Neaktívny', true),

-- Common validation SK
('validation.required', 'common', 'sk', 'Toto pole je povinné', true),
('validation.invalidEmail', 'common', 'sk', 'Neplatný email', true),
('validation.invalidPhone', 'common', 'sk', 'Neplatné telefónne číslo', true),
('validation.invalidIco', 'common', 'sk', 'Neplatné IČO', true),
('validation.invalidDic', 'common', 'sk', 'Neplatné DIČ', true),

-- Common general SK
('general.yes', 'common', 'sk', 'Áno', true),
('general.no', 'common', 'sk', 'Nie', true),
('general.optional', 'common', 'sk', 'Voliteľné', true),
('general.required', 'common', 'sk', 'Povinné', true),
('general.contractNumber', 'common', 'sk', 'Číslo zmluvy', true),
('general.lastSaved', 'common', 'sk', 'Naposledy uložené', true),
('general.autoSave', 'common', 'sk', 'Automatické ukladanie', true),

-- Welcome section SK
('welcome.title', 'common', 'sk', 'Registrácia bez stresu.', true),
('welcome.subtitle', 'common', 'sk', 'Vitaj v onboardingu budúcnosti.', true),
('welcome.heroDescription', 'common', 'sk', 'Moderná platforma pre jednoduché a rýchle spracovanie obchodných zmlúv a registrácií.', true),
('welcome.login.title', 'common', 'sk', 'Prihlásiť sa', true),
('welcome.login.description', 'common', 'sk', 'Pristúpte k svojmu účtu a pokračujte v práci', true),
('welcome.login.button', 'common', 'sk', 'Prihlásiť sa', true),
('welcome.onboarding.title', 'common', 'sk', 'Začať registráciu', true),
('welcome.onboarding.description', 'common', 'sk', 'Registrácia novej spoločnosti do systému', true),
('welcome.onboarding.button', 'common', 'sk', 'Začať proces', true),
('welcome.features.title', 'common', 'sk', 'Prečo Utopia?', true),
('welcome.features.fast.title', 'common', 'sk', 'Rýchle spracovanie', true),
('welcome.features.fast.description', 'common', 'sk', 'Automatizované procesy urýchľujú registráciu', true),
('welcome.features.secure.title', 'common', 'sk', 'Bezpečné', true),
('welcome.features.secure.description', 'common', 'sk', 'Najvyššie štandardy zabezpečenia dát', true),
('welcome.features.simple.title', 'common', 'sk', 'Jednoduché', true),
('welcome.features.simple.description', 'common', 'sk', 'Intuitívne rozhranie pre všetkých používateľov', true),
('welcome.selectRole', 'common', 'sk', 'Vyberte svoju rolu', true),
('welcome.backButton', 'common', 'sk', 'Späť', true),
('welcome.roles.admin.title', 'common', 'sk', 'Admin (ISO organizácia)', true),
('welcome.roles.admin.description', 'common', 'sk', 'Plný prístup k systému', true),
('welcome.roles.partner.title', 'common', 'sk', 'Obchodný partner', true),
('welcome.roles.partner.description', 'common', 'sk', 'Správa vlastných klientov', true),
('welcome.roles.merchant.title', 'common', 'sk', 'Klient (merchant)', true),
('welcome.roles.merchant.description', 'common', 'sk', 'Zobrazenie vlastných dát', true),
('welcome.footer', 'common', 'sk', 'Utopia Research Lab 2025', true),

-- English common translations
('buttons.next', 'common', 'en', 'Next', true),
('buttons.back', 'common', 'en', 'Back', true),
('buttons.save', 'common', 'en', 'Save', true),
('buttons.saveAndExit', 'common', 'en', 'Save and Exit', true),
('buttons.complete', 'common', 'en', 'Complete Registration', true),
('buttons.add', 'common', 'en', 'Add', true),
('buttons.remove', 'common', 'en', 'Remove', true),
('buttons.edit', 'common', 'en', 'Edit', true),
('buttons.cancel', 'common', 'en', 'Cancel', true),
('buttons.confirm', 'common', 'en', 'Confirm', true),
('buttons.close', 'common', 'en', 'Close', true),
('buttons.continue', 'common', 'en', 'Continue', true),
('buttons.saveSignature', 'common', 'en', 'Save Signature', true),
('buttons.delete', 'common', 'en', 'Delete', true),
('buttons.deleting', 'common', 'en', 'Deleting...', true),
('buttons.clearFilters', 'common', 'en', 'Clear Filters', true),

('navigation.step', 'common', 'en', 'Step', true),
('navigation.of', 'common', 'en', 'of', true),
('navigation.progress', 'common', 'en', 'Progress', true),
('navigation.completed', 'common', 'en', 'completed', true),
('navigation.steps', 'common', 'en', 'steps', true),
('navigation.overall', 'common', 'en', 'Overall Progress', true),

('status.saving', 'common', 'en', 'Saving...', true),
('status.saved', 'common', 'en', 'Saved', true),
('status.loading', 'common', 'en', 'Loading...', true),
('status.submitting', 'common', 'en', 'Submitting...', true),
('status.error', 'common', 'en', 'Error', true),
('status.success', 'common', 'en', 'Success', true),
('status.draft', 'common', 'en', 'Draft', true),
('status.completed', 'common', 'en', 'Completed', true),
('status.inProgress', 'common', 'en', 'In Progress', true),
('status.next', 'common', 'en', 'Next', true),
('status.partiallyComplete', 'common', 'en', 'Partially Complete', true),
('status.active', 'common', 'en', 'Active', true),
('status.inactive', 'common', 'en', 'Inactive', true),

('validation.required', 'common', 'en', 'This field is required', true),
('validation.invalidEmail', 'common', 'en', 'Invalid email', true),
('validation.invalidPhone', 'common', 'en', 'Invalid phone number', true),
('validation.invalidIco', 'common', 'en', 'Invalid ICO', true),
('validation.invalidDic', 'common', 'en', 'Invalid DIC', true),

('general.yes', 'common', 'en', 'Yes', true),
('general.no', 'common', 'en', 'No', true),
('general.optional', 'common', 'en', 'Optional', true),
('general.required', 'common', 'en', 'Required', true),
('general.contractNumber', 'common', 'en', 'Contract Number', true),
('general.lastSaved', 'common', 'en', 'Last Saved', true),
('general.autoSave', 'common', 'en', 'Auto Save', true);

-- Add admin navigation translations SK
INSERT INTO translations (key, namespace, language, value, is_system) VALUES
('navigation.dashboard', 'admin', 'sk', 'Dashboard', true),
('navigation.overview', 'admin', 'sk', 'Prehľad', true),
('navigation.merchants', 'admin', 'sk', 'Merchanti', true),
('navigation.allMerchants', 'admin', 'sk', 'Všetci merchanti', true),
('navigation.locations', 'admin', 'sk', 'Lokality', true),
('navigation.requests', 'admin', 'sk', 'Žiadosti', true),
('navigation.contracts', 'admin', 'sk', 'Zmluvy', true),
('navigation.myContracts', 'admin', 'sk', 'Moje zmluvy', true),
('navigation.oldContracts', 'admin', 'sk', 'Staré zmluvy', true),
('navigation.myOldContracts', 'admin', 'sk', 'Moje staré zmluvy', true),
('navigation.warehouse', 'admin', 'sk', 'Sklad', true),
('navigation.allItems', 'admin', 'sk', 'Všetky položky', true),
('navigation.solutions', 'admin', 'sk', 'Riešenia', true),
('navigation.categories', 'admin', 'sk', 'Kategórie', true),
('navigation.itemTypes', 'admin', 'sk', 'Typy položiek', true),
('navigation.addItem', 'admin', 'sk', 'Pridať položku', true),
('navigation.bulkOperations', 'admin', 'sk', 'Batch operácie', true),
('navigation.devices', 'admin', 'sk', 'Zariadenia', true),
('navigation.services', 'admin', 'sk', 'Služby', true),
('navigation.reporting', 'admin', 'sk', 'Reporting', true),
('navigation.reportsDashboard', 'admin', 'sk', 'Dashboard reportov', true),
('navigation.businessReports', 'admin', 'sk', 'Obchodné reporty', true),
('navigation.technicalReports', 'admin', 'sk', 'Technické reporty', true),
('navigation.organizations', 'admin', 'sk', 'Organizácie', true),
('navigation.organizationManagement', 'admin', 'sk', 'Správa organizácií', true),
('navigation.teamManagement', 'admin', 'sk', 'Správa tímov', true),
('navigation.organizationalStructure', 'admin', 'sk', 'Organizačná štruktúra', true),
('navigation.teamMembers', 'admin', 'sk', 'Členovia tímu', true),
('navigation.teamPerformance', 'admin', 'sk', 'Výkonnosť tímu', true),
('navigation.tasks', 'admin', 'sk', 'Úlohy', true),
('navigation.ticketingSystem', 'admin', 'sk', 'Ticketový systém', true),
('navigation.allTasks', 'admin', 'sk', 'Všetky úlohy', true),
('navigation.completedTasks', 'admin', 'sk', 'Dokončené úlohy', true),
('navigation.notifications', 'admin', 'sk', 'Notifikácie', true),
('navigation.settings', 'admin', 'sk', 'Nastavenia', true),
('navigation.applicationSettings', 'admin', 'sk', 'Nastavenia aplikácie', true),
('navigation.profileSettings', 'admin', 'sk', 'Nastavenia profilu', true),
('navigation.translations', 'admin', 'sk', 'Preklady', true),

-- Dashboard translations SK
('dashboard.title', 'admin', 'sk', 'Administratívny dashboard', true),
('dashboard.subtitle', 'admin', 'sk', 'Prehľad všetkých aktivít a štatistík', true),
('dashboard.newContract', 'admin', 'sk', 'Nová zmluva', true),
('dashboard.status.online', 'admin', 'sk', 'Online', true),

-- Settings SK
('settings.description', 'admin', 'sk', 'Spravujte nastavenia aplikácie a vášho profilu', true),

-- English admin translations
('navigation.dashboard', 'admin', 'en', 'Dashboard', true),
('navigation.overview', 'admin', 'en', 'Overview', true),
('navigation.merchants', 'admin', 'en', 'Merchants', true),
('navigation.allMerchants', 'admin', 'en', 'All Merchants', true),
('navigation.locations', 'admin', 'en', 'Locations', true),
('navigation.requests', 'admin', 'en', 'Requests', true),
('navigation.contracts', 'admin', 'en', 'Contracts', true),
('navigation.myContracts', 'admin', 'en', 'My Contracts', true),
('navigation.oldContracts', 'admin', 'en', 'Old Contracts', true),
('navigation.myOldContracts', 'admin', 'en', 'My Old Contracts', true),
('navigation.warehouse', 'admin', 'en', 'Warehouse', true),
('navigation.allItems', 'admin', 'en', 'All Items', true),
('navigation.solutions', 'admin', 'en', 'Solutions', true),
('navigation.categories', 'admin', 'en', 'Categories', true),
('navigation.itemTypes', 'admin', 'en', 'Item Types', true),
('navigation.addItem', 'admin', 'en', 'Add Item', true),
('navigation.bulkOperations', 'admin', 'en', 'Bulk Operations', true),
('navigation.devices', 'admin', 'en', 'Devices', true),
('navigation.services', 'admin', 'en', 'Services', true),
('navigation.reporting', 'admin', 'en', 'Reporting', true),
('navigation.reportsDashboard', 'admin', 'en', 'Reports Dashboard', true),
('navigation.businessReports', 'admin', 'en', 'Business Reports', true),
('navigation.technicalReports', 'admin', 'en', 'Technical Reports', true),
('navigation.organizations', 'admin', 'en', 'Organizations', true),
('navigation.organizationManagement', 'admin', 'en', 'Organization Management', true),
('navigation.teamManagement', 'admin', 'en', 'Team Management', true),
('navigation.organizationalStructure', 'admin', 'en', 'Organizational Structure', true),
('navigation.teamMembers', 'admin', 'en', 'Team Members', true),
('navigation.teamPerformance', 'admin', 'en', 'Team Performance', true),
('navigation.tasks', 'admin', 'en', 'Tasks', true),
('navigation.ticketingSystem', 'admin', 'en', 'Ticketing System', true),
('navigation.allTasks', 'admin', 'en', 'All Tasks', true),
('navigation.completedTasks', 'admin', 'en', 'Completed Tasks', true),
('navigation.notifications', 'admin', 'en', 'Notifications', true),
('navigation.settings', 'admin', 'en', 'Settings', true),
('navigation.applicationSettings', 'admin', 'en', 'Application Settings', true),
('navigation.profileSettings', 'admin', 'en', 'Profile Settings', true),
('navigation.translations', 'admin', 'en', 'Translations', true),

('dashboard.title', 'admin', 'en', 'Admin Dashboard', true),
('dashboard.subtitle', 'admin', 'en', 'Overview of all activities and statistics', true),
('dashboard.newContract', 'admin', 'en', 'New Contract', true),
('dashboard.status.online', 'admin', 'en', 'Online', true),

('settings.description', 'admin', 'en', 'Manage application and profile settings', true);