// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vspjxzbeooknotuxiefk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzcGp4emJlb29rbm90dXhpZWZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0OTI1ODEsImV4cCI6MjA2NTA2ODU4MX0.j0c8Eh4j4t5VORZUKYlxx2FJctdnp42K3_kTGoIiAkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);