// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdoofwbdkoimwijtqdav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkb29md2Jka29pbXdpanRxZGF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTU0NzQsImV4cCI6MjA2NDUzMTQ3NH0.6BroCR9ze36_LeUuzisMzKbmxYW5OM5M0uKv5ubjZgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);